export const SURVEY_LIST_REQUEST = 'SURVEY_LIST_REQUEST'
export const SURVEY_LIST_SUCCESS = 'SURVEY_LIST_SUCCESS'
export const SURVEY_LIST_FAIL = 'SURVEY_LIST_FAIL'

export const MY_SURVEY_LIST_REQUEST = 'MY_SURVEY_LIST_REQUEST'
export const MY_SURVEY_LIST_SUCCESS = 'MY_SURVEY_LIST_SUCCESS'
export const MY_SURVEY_LIST_FAIL = 'MY_SURVEY_LIST_FAIL'

export const SURVEY_DETAILS_REQUEST = 'SURVEY_DETAILS_REQUEST'
export const SURVEY_DETAILS_SUCCESS = 'SURVEY_DETAILS_SUCCESS'
export const SURVEY_DETAILS_FAIL = 'SURVEY_DETAILS_FAIL'

export const SURVEY_DELETE_REQUEST = 'SURVEY_DELETE_REQUEST'
export const SURVEY_DELETE_SUCCESS = 'SURVEY_DELETE_SUCCESS'
export const SURVEY_DELETE_FAIL = 'SURVEY_DELETE_FAIL'

export const SURVEY_FILL_REQUEST = 'SURVEY_FILL_REQUEST'
export const SURVEY_FILL_SUCCESS = 'SURVEY_FILL_SUCCESS'
export const SURVEY_FILL_FAIL = 'SURVEY_FILL_FAIL'

export const SURVEY_FILLED_LIST_REQUEST = 'SURVEY_FILLED_LIST_REQUEST'
export const SURVEY_FILLED_LIST_SUCCESS = 'SURVEY_FILLED_LIST_SUCCESS'
export const SURVEY_FILLED_LIST_FAIL = 'SURVEY_FILLED_LIST_FAIL'

export const SURVEY_CREATE_REQUEST = 'SURVEY_CREATE_REQUEST'
export const SURVEY_CREATE_SUCCESS = 'SURVEY_CREATE_SUCCESS'
export const SURVEY_CREATE_FAIL = 'SURVEY_CREATE_FAIL'
export const SURVEY_CREATE_RESET = 'SURVEY_CREATE_RESET'

export const SURVEY_UPDATE_REQUEST = 'SURVEY_UPDATE_REQUEST'
export const SURVEY_UPDATE_SUCCESS = 'SURVEY_UPDATE_SUCCESS'
export const SURVEY_UPDATE_FAIL = 'SURVEY_UPDATE_FAIL'
export const SURVEY_UPDATE_RESET = 'SURVEY_UPDATE_RESET'