# Generated by Django 4.1.2 on 2023-01-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='pub_date',
        ),
    ]
