# Generated by Django 4.1.2 on 2022-10-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_text', 'survey')},
        ),
    ]
