# Generated by Django 4.1.2 on 2023-01-19 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_filledsurvey_date_taken_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
